---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-jobs-cluster
  namespace: demo-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobs-reader-cluster
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-jobs-cluster
subjects:
- kind: ServiceAccount
  name: demo-jobs-cluster
  namespace: demo-jobs
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: jobs-reader-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-jobs-namespace
  namespace: demo-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-reader-namespace
  namespace: demo-jobs
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-jobs-namespace
  namespace: demo-jobs
subjects:
- kind: ServiceAccount
  name: demo-jobs-namespace
  namespace: demo-jobs
  apiGroup: ""
roleRef:
  kind: Role
  name: jobs-reader-namespace
  apiGroup: rbac.authorization.k8s.io
